### ISSUE TITLE
Authorship of patches

### ISSUE THREAD

**Issue by torvic9** [CachyOS/kernel-patches#11]
Hi,

I don't use CachyOS or its kernel and just stumbled upon these patchfiles by curiosity.

I would like to know whether you could keep the original authorship of the patches you use (ideally with the original commit messages), instead of concatenating them and signing off.

It is very hard to track where all this stuff comes from (and I do see some fragments of my own stuff).

Cheers

**Comment by ptr1337** [comment]
Hi,

Everything is tracked down here, with each branches:
https://github.com/CachyOS/linux

Patches which are 000x-branch name in kernel-patches are simply signed to create the cachyos-base-all patchset.
As long commits dont need to be rebased, the orignal commit author will stay

Regards

**Comment by torvic9** [comment]
Got it, thank you.

Looking at Piotr's "zstd compression level" patches, I must say that they look *very* similar to mine:

https://gitlab.com/torvic9/linux-stable/-/commit/5acb3ab4d9917e6a580412257271a7ebafe1b8f0
https://gitlab.com/torvic9/linux-stable/-/commit/c7db7db846fa1a7b31e4b230510b3bb9a400bc36
https://gitlab.com/torvic9/linux-stable/-/commit/3588cab27515b0e3c625536f83a3eb95f5e541c0

I know that Piotr worked on this in the past concurrently (and sometimes together) with me, but still...

**Comment by sirlucjan** [comment]
Yes, it's similar. I added ultra compression level and changed some values.

**Comment by torvic9** [comment]
Did you come up with the same variable name as me?
I mean commit "Kconfig, zstd: Rename COMP_VAL to COMPRESSION_LEVEL" for example...the only difference being *LEVEL vs. *LVL.

**Comment by sirlucjan** [comment]
Yes. I will add information about you in patch when I will come back to home.

**Comment by sirlucjan** [comment]
@torvic9 Here you go: https://github.com/CachyOS/linux/compare/ec2516148da0...ada3ead88c6e

I added all my changes to separate patch:

https://github.com/CachyOS/linux/commit/ada3ead88c6e272787e2d427479ff06689eb4299

**Comment by torvic9** [comment]
Yes, that's good, I'm happy with that.

Thank you, I'll close this issue.

**Comment by sirlucjan** [comment]
Thank you for reporting and sorry for the inconvenience.
