### ISSUE TITLE
PRJC for linux 6.3

### ISSUE THREAD

**Issue by blacksky3** [CachyOS/kernel-patches#13]
Hi prjc patch fail to build kernel with this error :

MODPOST Module.symvers
ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!

You should add the patch mentionned in https://gitlab.com/alfredchen/linux-prjc/-/issues/81

Thanks

**Comment by sirlucjan** [comment]
Hi.

Could you test? I've added to -dev directory. 

https://github.com/CachyOS/kernel-patches/tree/master/6.3/sched-dev

**Comment by blacksky3** [comment]
Hi I have already tested it and it's in the AUR 
https://aur.archlinux.org/packages/linux-pds
https://aur.archlinux.org/packages/linux-bmq

**Comment by ptr1337** [comment]
> Hi prjc patch fail to build kernel with this error :
> 
> MODPOST Module.symvers ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!
> 
> You should add the patch mentionned in https://gitlab.com/alfredchen/linux-prjc/-/issues/81
> 
> Thanks

The above way is not a fix for this, its just a workaround.
Just disable NUMA and it should be good to go.
