### ISSUE TITLE
kernel 6.4 bcachefs patch is not working

### ISSUE THREAD

**Issue by shanoaice** [CachyOS/kernel-patches#17]
I am compiling linux-cachyos-tt with bcachefs support enabled, however the patch don't seem to apply successfully. `mm/slab.h.rej` indicates that this hunk fails to apply:
```diff
@@ -684,6 +828,7 @@ static inline void slab_post_alloc_hook(struct kmem_cache *s,
 					unsigned int orig_size)
 {
 	unsigned int zero_size = s->object_size;
+	struct slabobj_ext *obj_exts;
 	size_t i;
```
after searching the source code, this hunk seems to be missing one line:
```c
bool kasan_init = init;
```
it probably should be like this:
```diff
@@ -684,6 +828,7 @@ static inline void slab_post_alloc_hook(struct kmem_cache *s,
 					unsigned int orig_size)
 {
 	unsigned int zero_size = s->object_size;
+	struct slabobj_ext *obj_exts;
 	bool kasan_init = init;
 	size_t i;
```

**Comment by ptr1337** [comment]
Hi,

Thanks for reporting! We will fixup this soon.

**Comment by sirlucjan** [comment]
Could you check? https://github.com/CachyOS/kernel-patches/commit/81196dd90b2dd4f7becbff3c051fa3dfe2a2f015

**Comment by shanoaice** [comment]
> Could you check? [81196dd](https://github.com/CachyOS/kernel-patches/commit/81196dd90b2dd4f7becbff3c051fa3dfe2a2f015)

Yes, confirmed that patch application succeeds. Thanks.

**Comment by sirlucjan** [comment]
Could you close issue then?
