### ISSUE TITLE
6.0.0 stable won't boot at all with cachyos patchset

### ISSUE THREAD

**Issue by sandikata** [CachyOS/kernel-patches#3]
Hello, 

Facing same issue as before (on 5.15 were kernel not boot at all with cachyos patch).

Cannot collect any logs, as it stuck on grub bootloader (loading kernel, loading initramfs) and only hard reset is option.
PS: Using latest cachyos patch (updated 8 hours ago)

Regards,
Rosen Aleksandrov

**Comment by ptr1337** [comment]
Hey!

Ive already noticed the same, this came actually between the rc7 and stable. At the rc7 the patchset worked fine, and somehow a merge did broke this.
I actually already found the patch, which doing this issue and working now on which exact patch of the branch, brings the unbootable kernel.

Actually I really suspect the clearlinux patch, but we will see.
I will update the patchset, as soon I found the culprit. 

Regards

**Comment by sandikata** [comment]
Why we even add clearos patches ? They're designed for intel only cpu's and could break a lot of things in AMD platforms.

**Comment by ptr1337** [comment]
These are sorted patches from clearlinux.
And yes, clearlinux does focus on Intel CPU's, but they also support and focus on AMD CPU's nowadays. Its even offically supported, and @sirlucjan and me using this patchset since years (since they dont break anything with amd, actually INTEL does also not boot)

Dont know where you get this from

**Comment by sirlucjan** [comment]
We have been using clearlinux almost from the beginning, and so far no one has complained that anything is not working for them. Even quite a many people asked where they could find this patch with us. If clearlinux is indeed causing problems with 6.0 then we will simply remove this patchset until it is ported to a proper version.

**Comment by sandikata** [comment]
Well, i can report with old cachyos patch (30 September) no issue at all, it boots.

https://gist.github.com/sandikata/56bcb72462ab311573c883204236d3e6

**Comment by ptr1337** [comment]
https://github.com/CachyOS/kernel-patches/commit/46cc5dae4bd0b76d1e112bcf0136068aead7ed59

Fixed
