### ISSUE TITLE
Usage of unused patches in linux-cachyos

### ISSUE THREAD

**Issue by corporal9736** [CachyOS/kernel-patches#35]
There are some patches that never show up in [linux-cachyos](https://github.com/CachyOS/linux-cachyos), such as 6.5/misc/0001-high-hz.patch. When and how are these patches used?

**Comment by ptr1337** [comment]
> There are some patches that never show up in [linux-cachyos](https://github.com/CachyOS/linux-cachyos), such as 6.5/misc/0001-high-hz.patch. When and how are these patches used?

Some people over the time requesting some patches or some are testing patches from us, like the intel thread director,clang-pgo,... .

The high-hz patch is really not recommended to use.

**Comment by corporal9736** [comment]
Got it, many thanks!
