### ISSUE TITLE
high-hz patch on kernel >= 6.6.x

### ISSUE THREAD

**Issue by olm52** [CachyOS/kernel-patches#36]
I have tested the previous high-hz patch on kernel 6.6.1
There is an error about zcrypt_cex2c.c
Strangely that file in last kernel is empty.

I have removed the relevant section

`674a675,690
> diff --git a/drivers/s390/crypto/zcrypt_cex2c.c b/drivers/s390/crypto/zcrypt_cex2c.c
> index 251b5bd3d19c28..022cbae929a9d0 100644
> --- a/drivers/s390/crypto/zcrypt_cex2c.c
> +++ b/drivers/s390/crypto/zcrypt_cex2c.c
> @@ -211,7 +211,11 @@ static int zcrypt_cex2c_rng_supported(struct ap_queue *aq)
>  
>       /* Wait for the test message to complete. */
>       for (i = 0; i < 2 * HZ; i++) {
> +#if HZ >= 1000
> +             msleep(1);
> +#else
>               msleep(1000 / HZ);
> +#endif
>               rc = ap_recv(aq->qid, &psmid, ap_msg.msg, ap_msg.bufsize);
>               if (rc == 0 && psmid == 0x0102030405060708UL)
>                       break;
`

and now is applying fine. Kernel is booting without problems.
Not sure that some other modifications are necessary.

Do you plan to release an updated patch?

**Comment by Plavil** [comment]
Can you please the share the fixed patch?

**Comment by olm52** [comment]
You can do yourself very easily removing the zcrypt_cex2c.c section displayed above of 6.5.z patch

**Comment by ptr1337** [comment]
No, we dont plan to add it again.
