### ISSUE TITLE
AMDGPU HDR patch causes issues, possibly involving my VRR display

### ISSUE THREAD

**Issue by kode54** [CachyOS/kernel-patches#38]
I have a Radeon RX 6700-XT, and two monitors: An LG 24UD58-B, which is 3840x2160 panel that supports up to 60Hz and supports optional VRR range of 40-60Hz, and a Dell P2414H, a 1920x1080 panel that supports up to 60Hz and no VRR.

The issue presents regardless of whether I enable VRR support in the monitor, though. It causes, for example, kmscube to redraw at half the monitor's refresh rate. It also causes redrawing on Wayfire to operate at 30Hz, and almost immediately promote to 60Hz when I move windows to the secondary display.

Both monitors report max_bpc of 8 without the patch. The patch exposes a configuration option related to the Steam Deck, which shows a default choice of N, which I left as N each time I built during my unfortunate attempt at bisecting rc4 to rc5. Turns out I didn't even know I was hit by this patch, since the rc4 I experienced was with a fairly default Linux-TkG configuration, which doesn't include the HDR patch set.

Edit: Upon further reflection, I noted that it didn't break with kernel 6.6. I compared the HDR patch between the two, and noted that the 6.7 patch force enables VRR for page flipping. My compositor does not have support for VRR at all. This is probably bad for scenarios where VRR has been force enabled.

**Comment by ptr1337** [comment]
Hi,
Thanks for your report!

I guess you are talking about the 6.7 AMD HDR Patchset?

**Comment by kode54** [comment]
Just in case, I've also asked the wlroots IRC channel what would happen in the scenario that the 6.7 patch creates. It appears to be force enabling VRR in both the flipping IRQ and the present functions, without reporting to the DRM client(s) that VRR is enabled via the flag.

**Comment by GloriousEggroll** [comment]
> Just in case, I've also asked the wlroots IRC channel what would happen in the scenario that the 6.7 patch creates. It appears to be force enabling VRR in both the flipping IRQ and the present functions, without reporting to the DRM client(s) that VRR is enabled via the flag.

last i checked cachy was missing a patch.
this is what broke it on nobara originally (was reported by rog ally users):

https://gitlab.com/evlaV/linux-integration/-/commit/32d8309584145f531b46e8c1a72c86494e72160d

and this is what fixed it:

https://gitlab.com/evlaV/linux-integration/-/commit/2bfd05863fff384619dea44bafa98ba0e6a5cdf4

**Comment by ptr1337** [comment]
@kode54 

Could you please add following patch on top of the "amd-hdr" patch and check if it fixes it for you?

```diff
From 16c0e3dc2612bdd5d26aeac790c132c566d2d377 Mon Sep 17 00:00:00 2001
From: Joshua Ashton <joshua@froggi.es>
Date: Sun, 3 Dec 2023 11:35:06 +0000
Subject: [PATCH] drm/amd/display: Revert some of the vrr always on hack

Fixes frame timings on some non)-VRR external displays going all whacky.

This makes us not use the late vblank irq handler (backporch line 0) and instead send the vblank event immediately on page flip when we know where the vblank is going to be.

Should also improve latency/stutter on internal display potentially too.
---
 drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c b/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
index f10e16dc9d39..eb256f32bc9f 100644
--- a/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
+++ b/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
@@ -445,7 +445,7 @@ static void dm_pflip_high_irq(void *interrupt_params)
 
 	WARN_ON(!e);
 
-	vrr_active = true;//amdgpu_dm_crtc_vrr_active_irq(amdgpu_crtc);
+	vrr_active = amdgpu_dm_crtc_vrr_active_irq(amdgpu_crtc);
 
 	/* Fixed refresh rate, or VRR scanout position outside front-porch? */
 	if (!vrr_active ||
@@ -542,11 +542,11 @@ static void dm_vupdate_high_irq(void *interrupt_params)
 		 * page-flip completion events that have been queued to us
 		 * if a pageflip happened inside front-porch.
 		 */
-		if (true) {
+		if (vrr_active) {
 			amdgpu_dm_crtc_handle_vblank(acrtc);
 
 			/* BTR processing for pre-DCE12 ASICs */
-			if (vrr_active && acrtc->dm_irq_params.stream &&
+			if (acrtc->dm_irq_params.stream &&
 			    adev->family < AMDGPU_FAMILY_AI) {
 				spin_lock_irqsave(&adev_to_drm(adev)->event_lock, flags);
 				mod_freesync_handle_v_update(
-- 
2.43.0

```

**Comment by kode54** [comment]
Yes, this seems to have fixed the issue.

Though rather than apply this patch on top of the existing one, I opted to edit the current base patch by deleting the two blocks that this reverts. Of course, you'll have to regenerate the whole patch instead, since it includes a summary section as well, and simply deleting two blocks will not update the summary.

**Comment by ptr1337** [comment]
Patch landed in rc6. Closing here.

Thanks for reporting!
