### ISSUE TITLE
[Request] It's possible to bring the TT High Hertz patch to newer kernels, like 6.1?

### ISSUE THREAD

**Issue by lphd12** [CachyOS/kernel-patches#4]
Hello, the current high hertz patch is only available on older kernels (5.15 or 5.19), i would like to know if this patch could be rebased on newer kernels, like the 6.1, it would be possible? thanks in advance! :-)

**Comment by ptr1337** [comment]
Yes, I can update it later

**Comment by ptr1337** [comment]
https://github.com/CachyOS/kernel-patches/commit/98f9d999fb2f7a62db3cc013060218a703d74b9f

Added
