### ISSUE TITLE
Please keep lts (6.6) patches updated

### ISSUE THREAD

**Issue by dim-geo** [CachyOS/kernel-patches#47]
Hi, can you please keep lts patches updated?
6.6 uses older bore-scheduler.

**Comment by dim-geo** [comment]
Nice, I see that bore patches are now 4.1.3 !
What about bbrv3?


Στις Τετ, 24 Ιαν 2024, 17:21 ο χρήστης Piotr Górski <
***@***.***> έγραψε:

**Comment by leonpano2006** [comment]
a lot of patch are incompatible with 6.6.18

**Comment by ptr1337** [comment]
> a lot of patch is incompatible with 6.6.18

These patches are used in the linux-cachyos-lts kernel, which gets updated once a month. Please wait till we update our LTS kernel.

**Comment by leonpano2006** [comment]
> > a lot of patch is incompatible with 6.6.18
> 
> These patches are used in the linux-cachyos-lts kernel, which gets updated once a month. Please wait till we update our LTS kernel.

ok
since i uses these patch on other linux systems
ex. Rhel9

**Comment by ptr1337** [comment]
All of them are updated.

**Comment by leonpano2006** [comment]
> All of them are updated.

6.6.20?

**Comment by ptr1337** [comment]
yes
