### ISSUE TITLE
Optimization question

### ISSUE THREAD

**Issue by wctrl** [CachyOS/kernel-patches#54]
Hi, found this repo interesting, will [this](https://github.com/CachyOS/kernel-patches/blob/master/6.6/misc/0001-Add-extra-GCC-optimization-flags.patch) work with LLVM? Or it will be useless with already defined `-march=whatever`? Also I noticed that [there](https://github.com/ClangBuiltLinux/linux/issues/1074#issuecomment-1875507294) was a discussion about PGO from your patches, does it still exist here?
Thanks

**Comment by ptr1337** [comment]
> Hi, found this repo interesting, will [this](https://github.com/CachyOS/kernel-patches/blob/master/6.6/misc/0001-Add-extra-GCC-optimization-flags.patch) work with LLVM? Or it will be useless with already defined `-march=whatever`? Also I noticed that [there](https://github.com/ClangBuiltLinux/linux/issues/1074#issuecomment-1875507294) was a discussion about PGO from your patches, does it still exist here? Thanks

Hi,
We have moved the first patch out, that only if GCC is used it will use it:
https://github.com/CachyOS/linux/blob/6.8/cachy/Makefile#L1157-L1160

There is for some older Kernel Versions PGO available (it should be under the misc folder), but generally the profiling is weird with it, since the profile doesnt change after boot.
Personally I also did not saw any performance improvements from it in my common benchmark.

Actually BOLT is working on kernel support to optimize it, but it isnt ready.

**Comment by wctrl** [comment]
> Personally I also did not saw any performance improvements from it in my common benchmark.

This is a little sad, since clang with the same PGO looks impressive.


I was also interested in the patch for zstd, it's upstream, right? Is there something similar for lz4? At least the latest versions have improved the speed, meanwhile the kernel still have lz4 from 2016.

**Comment by ptr1337** [comment]
> > Personally I also did not saw any performance improvements from it in my common benchmark.
> 
> This is a little sad, since clang with the same PGO looks impressive.
> 
> I was also interested in the patch for zstd, it's upstream, right? Is there something similar for lz4? At least the latest versions have improved the speed, meanwhile the kernel still have lz4 from 2016.

There is a script to generate a kernel patch from upstream. The current patch in 6.8 and 6.9 tree updates it to the 1.5.6 API.
Related to lz4 - I dont know. Would need to look into.

**Comment by wctrl** [comment]
Ah alright. Backing to the kernel version, I can guess that this project was created after 2017, do you have or did you had patches for 4.14?

**Comment by ptr1337** [comment]
> Ah alright. Backing to the kernel version, I can guess that this project was created after 2017, do you have or did you had patches for 4.14?

We dont maintain old Kernels, besides the newest LTS. All other stuff gets deprecated over time.
So currently supportd:
6.6
6.8
6.9rc

**Comment by wctrl** [comment]
There **was** patches for 4.14? Or never?

**Comment by ptr1337** [comment]
> There **was** patches for 4.14? Or never?

No, there are now 4.14 patches currently.
Probably youre asking for android, right?

**Comment by wctrl** [comment]
Yes, due big vendor issues there's no way to bump kernel. In fact, I know where to get specific ones for my device/vendor. I'd like to see something more generic like these patches.
