### ISSUE TITLE
[Request] Inquiry Regarding Support for Latest Linux-drm Upstream Patch for AMD GPU

### ISSUE THREAD

**Issue by skygrango** [CachyOS/kernel-patches#55]
Dear,
I am reaching out to inquire about the possibility of integrating support for the latest upstream patch tagged `amd-drm-next-6.10-2024-04-26`, which I noticed was recently updated on the [freedesktop.org GitLab](https://gitlab.freedesktop.org/agd5f/linux/-/tags).

It includes fixes for AMD VRR, which seem very useful for gaming, as detailed [here](https://gitlab.freedesktop.org/drm/amd/-/issues/2186#note_2368021).

Is there any interest in supporting this patch in cachyos ?

**Comment by ptr1337** [comment]
Hi,

I will look into these 3 patches, mentioned in the note on gitlab for the next release.
We wont pull in a whole branch, since this can often come with bad regressions.

**Comment by skygrango** [comment]
> Hi,
> 
> I will look into these 3 patches, mentioned in the note on gitlab for the next release. We wont pull in a whole branch, since this can often come with bad regressions.

This is a very solid choice, thank you for your support

**Comment by ptr1337** [comment]
> > Hi,
> > I will look into these 3 patches, mentioned in the note on gitlab for the next release. We wont pull in a whole branch, since this can often come with bad regressions.
> 
> This is a very solid choice, thank you for your support

Do you know if they are merged in the 6.9 Tree?

**Comment by skygrango** [comment]
> Do you know if they are merged in the 6.9 Tree?

I check here [kernel mail list](https://lore.kernel.org/lkml/CAPM=9ty6LzXnyr5J1RrR8xRdiRcooTkoPuq9m108mUEsF7R98g@mail.gmail.com/T/) and [gitlab](https://gitlab.freedesktop.org/drm/kernel/-/blob/drm-fixes-2024-05-03/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c?ref_type=tags) `drm-fixes-2024-05-03`
and then search `dc_stream_set_cursor_position(dm_old_crtc_state->stream, &position)`

the answer should be NO. :)

**Comment by skygrango** [comment]
I'm not sure if AMD plans to backport this.
You can choose whether we need to provide this VRR repair in advance according to your profession.

**Comment by ptr1337** [comment]
> I'm not sure if AMD plans to backport this. You can choose whether we need to provide this VRR repair in advance according to your profession.

Applied on 6.9 Material.
Kernel will be in the repository in around 30 Minutes. Please test and if you face any regressions and if the VRR issue is fixed.

https://github.com/CachyOS/kernel-patches/commit/796eac6a68c9736b9555b798bcd1deee2e86cb80

**Comment by skygrango** [comment]
the newest commit should be this [one](https://gitlab.freedesktop.org/agd5f/linux/-/commit/66eba12a5482b79ed8cc45ae6f370b117b8e0507)

title :  `drm/amd/display: Do cursor programming with rest of pipe`

**Comment by ptr1337** [comment]
> the newest commit should be this [one](https://gitlab.freedesktop.org/agd5f/linux/-/commit/66eba12a5482b79ed8cc45ae6f370b117b8e0507)
> 
> title : `drm/amd/display: Do cursor programming with rest of pipe`

Oh, so its not these three commits from the link above?

**Comment by skygrango** [comment]
> > the newest commit should be this [one](https://gitlab.freedesktop.org/agd5f/linux/-/commit/66eba12a5482b79ed8cc45ae6f370b117b8e0507)
> > title : `drm/amd/display: Do cursor programming with rest of pipe`
> 
> Oh, so its not these three commits from the link above?

Oh, don’t get me wrong, I’m just telling you where their latest patch is.

I took a quick look and it looks like the similarity is pretty high

**Comment by skygrango** [comment]
> > I'm not sure if AMD plans to backport this. You can choose whether we need to provide this VRR repair in advance according to your profession.
> 
> Applied on 6.9 Material. Kernel will be in the repository in around 30 Minutes. Please test and if you face any regressions and if the VRR issue is fixed.
> 
> [796eac6](https://github.com/CachyOS/kernel-patches/commit/796eac6a68c9736b9555b798bcd1deee2e86cb80)

Thank you for your support :), I should have time to do some tests today

**Comment by ptr1337** [comment]
> > > I'm not sure if AMD plans to backport this. You can choose whether we need to provide this VRR repair in advance according to your profession.
> > 
> > 
> > Applied on 6.9 Material. Kernel will be in the repository in around 30 Minutes. Please test and if you face any regressions and if the VRR issue is fixed.
> > [796eac6](https://github.com/CachyOS/kernel-patches/commit/796eac6a68c9736b9555b798bcd1deee2e86cb80)
> 
> Thank you for your support :), I should have time to do some tests today

Do you were able to verify if this works correctly?
If yes, then you can close here. I wont backport it to 6.8, since in a week we will update the kernel anyways to 6.9 and then it should be fine.

**Comment by skygrango** [comment]
> Do you were able to verify if this works correctly? If yes, then you can close here. I wont backport it to 6.8, since in a week we will update the kernel anyways to 6.9 and then it should be fine.

I'm testing, everything seems to be fine following env
```
KWIN_DRM_DELAY_VRR_CURSOR_UPDATES=1
KWIN_DRM_DONT_FORCE_AMD_SW_CURSOR=1
```
This effectively reduces stuttering for me
If no observable regression occurs today, I will close this issue. 
Thanks for reminding !

**Comment by skygrango** [comment]
No obvious errors observed for me

I posted a [reddit](https://www.reddit.com/r/linux_gaming/comments/1cks9js/kdecachyosarch_amd_vrr_finally_works_properly/) asking anyone who is interested to try it out, but no regression reports have been received so far.

I think the current situation is good enough for me

close issue first, and thank you for support !

**Comment by ptr1337** [comment]
> No obvious errors observed for me
> 
> I posted a [reddit](https://www.reddit.com/r/linux_gaming/comments/1cks9js/kdecachyosarch_amd_vrr_finally_works_properly/) asking anyone who is interested to try it out, but no regression reports have been received so far.
> 
> I think the current situation is good enough for me
> 
> close issue first, and thank you for support !

Thanks for the info.
FYI, related to the recent AMD regression there was a commit in rc7 https://github.com/CachyOS/linux/commit/705d0480e6ae5a73ca3a9c04316d0678e19a46ed , which seems to fix the issue.
Sadly I can not test it, but ive reverted the revert related to the game start regression.

This landed now in rc7 Kernel and should be soon in the repository.

Thanks for your post! I saw it today after the work.
