### ISSUE TITLE
is there gcc-lto patch for 6.6 or latest?

### ISSUE THREAD

**Issue by leonpano2006** [CachyOS/kernel-patches#56]
i checked in cachyos repo have lto kernels but i didn't see any patch for lto in 6.6 or 6.8 and 6.9
is now cachyos lto kernel build by clang? or just patch is not public or is an error in cachyos's repo

**Comment by sirlucjan** [comment]
That's right, we dropped support for this patch - it was no longer developed. kernels with suffix lto have always been compiled with clang, we have never used this patch in production.

**Comment by leonpano2006** [comment]
btw
why when i tried to use lto on clang with menuconfig lto have no options?
did i forget something?
and i suggest to give better information for which kernel to use in cachyos's repo (there are too many kernel packages)
