### ISSUE TITLE
Problem compiling 6.9.4

### ISSUE THREAD

**Issue by xuanruiqi** [CachyOS/kernel-patches#63]
I get the following error:
```
make[2]: *** [scripts/Makefile.modfinal:56: fs/nls/nls_ucs2_utils.ko] Error 139
make[2]: *** Deleting file 'fs/nls/nls_ucs2_utils.ko'
make[2]: *** Waiting for unfinished jobs....
```
with LTO turned on. Haven't tried LTO off yet.

**Comment by ptr1337** [comment]
Downgrade your pahole version. Ive already reported it to clangbuiltlinux.

**Comment by xuanruiqi** [comment]
Thanks. It builds. Just asking, will everything be fine if I upgrade it back after building my kernel?

**Comment by ptr1337** [comment]
Its fine

**Comment by xuanruiqi** [comment]
Same problem with 6.9.5, guess its still not fixed
Could you post a link to the upstream (clangbuiltlinux) issue?

**Comment by sirlucjan** [comment]
We've to added new pahole to repo. Could you try?

**Comment by xuanruiqi** [comment]
I am on Arch and not the CachyOS repos, so I'll have to rebuild pahole myself. I will try to do so and report back.

**Comment by xuanruiqi** [comment]
Said patch indeed fixes the build process. Hopefully it will land in the next pahole version.
