### ISSUE TITLE
A patch is needed when compiling with LTO on AMD systems

### ISSUE THREAD

**Issue by xuanruiqi** [CachyOS/kernel-patches#65]
See ClangBuiltLinux/linux#1987 and llvm/llvm-project#72026. This patch should fix the issue:

```
diff --git a/net/ipv6/Makefile b/net/ipv6/Makefile
index d283c59df4c1..3840ded8c34a 100644
--- a/net/ipv6/Makefile
+++ b/net/ipv6/Makefile
@@ -3,6 +3,13 @@
 # Makefile for the Linux TCP/IP (INET6) layer.
 #
 
+# temporary workaround for clang/lld-18 with -march/-mtune=znver2
+# clangbuiltlinux issue 1987
+ifeq ($(call test-ge, $(CONFIG_CLANG_VERSION), 180000),y)
+badparms = -march=znver2 -mtune=znver2
+KBUILD_CFLAGS :=	$(filter-out $(badparams), $(KBUILD_CFLAGS))
+endif
+
 obj-$(CONFIG_IPV6) += ipv6.o
 
 ipv6-y :=	af_inet6.o anycast.o ip6_output.o ip6_input.o addrconf.o \
```

**Comment by ptr1337** [comment]
> See [ClangBuiltLinux/linux#1987](https://github.com/ClangBuiltLinux/linux/issues/1987) and [llvm/llvm-project#72026](https://github.com/llvm/llvm-project/issues/72026). This patch should fix the issue:
> 
> ```
> diff --git a/net/ipv6/Makefile b/net/ipv6/Makefile
> index d283c59df4c1..3840ded8c34a 100644
> --- a/net/ipv6/Makefile
> +++ b/net/ipv6/Makefile
> @@ -3,6 +3,13 @@
>  # Makefile for the Linux TCP/IP (INET6) layer.
>  #
>  
> +# temporary workaround for clang/lld-18 with -march/-mtune=znver2
> +# clangbuiltlinux issue 1987
> +ifeq ($(call test-ge, $(CONFIG_CLANG_VERSION), 180000),y)
> +badparms = -march=znver2 -mtune=znver2
> +KBUILD_CFLAGS :=	$(filter-out $(badparams), $(KBUILD_CFLAGS))
> +endif
> +
>  obj-$(CONFIG_IPV6) += ipv6.o
>  
>  ipv6-y :=	af_inet6.o anycast.o ip6_output.o ip6_input.o addrconf.o \
> ```

Hi,

Thanks for providing the patch, but we will not provide this in the patchset, since the above one would also only apply if znver2 is set.
CachyOS patches LLVM with the fixing patchset, so there for we do not need it here, also see:

https://github.com/CachyOS/CachyOS-PKGBUILDS/commit/36484bc234f5613b4e689aa581fb3b9ae92a3933

**Comment by xuanruiqi** [comment]
OK, I have asked upstream to backport this commit too
