### ISSUE TITLE
How to choose kernel compression level?

### ISSUE THREAD

**Issue by leonpano2006** [CachyOS/kernel-patches#68]
i didn't see a place can choose what should initramfs being compressed
and vmlinux and kernel modules

**Comment by ptr1337** [comment]
For the modules its handled here:
https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L613

**Comment by leonpano2006** [comment]
can we use zstd22?
i wish option can be chosen form menuconfig

**Comment by 1Naim** [comment]
> can we use zstd22?

Yes, just change the corresponding lines in the PKGBUILD (L619, L732, L750, 768) to 22 [PKGBUILD](https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD)
