### ISSUE TITLE
Lenovo Legion patch missing from kernels > 6.7

### ISSUE THREAD

**Issue by emilf** [CachyOS/kernel-patches#71]
It is claimed in the README in https://github.com/johnfanv2/LenovoLegionLinux that the dkms package is not required for CachyOS so I uninstalled it on my machine, but then legion features stopped working.
I looked into it briefly and it seems that legion patches are no longer included in kernels post 6.7.

You can verify if the legion driver is active by checking if /sys/kernel/debug/legion exists.

For the record, I'm running the current 6.10.9-2-cachyos kernel.

**Comment by ptr1337** [comment]
Hey,

We have dropped the patchset, because the driver got loaded, even if there was no lenovo hardware available.

**Comment by emilf** [comment]
Thanks for the reply. I'll ask them to update their README

**Comment by johnfanv2** [comment]
> Hey,
> 
> We have dropped the patchset, because the driver got loaded, even if there was no lenovo hardware available.

That is pretty interesting and should never happen. Do you have more details or a user report for that?

The driver is probed when there is a device 'PNP0C0' and then it checks if via DMI if the the vendor is `LENOVO` and the BIOS version is in a list of supported BIOS versions (e.g. `HHCN`).

**Comment by ptr1337** [comment]
> > Hey,
> > We have dropped the patchset, because the driver got loaded, even if there was no lenovo hardware available.
> 
> That is pretty interesting and should never happen. Do you have more details or a user report for that?
> 
> The driver is probed when there is a device `PNP0C0`. Then the driver checks if the the vendor is `LENOVO` and the BIOS version is in a list of supported BIOS versions (e.g. `HHCN`) via DMI. If this is check is not successful the probe aborts and it will unload.

Hi,

This was mainly found on the Steam Deck, when we started to work on the cachyos handheld option. Basically the driver got probed but then failed with an error. Generally this is not problematic, but I dont like to have from a patchset side introduced errors in the kernel.

**Comment by No-Biggie805** [comment]
Suggestion, how about making it available as a binary package of the  existing AUR, for the cachyOS repos?
Many thanks.

**Comment by 1Naim** [comment]
It definitely doesn't hurt adding it to our repos, but you can say the same to installing it directly from the AUR. I say this because the AUR package does nothing more than:
1. Cloning the repo
2. Setting the pkgver
3. Installing files to the package

There is no building involved.

**Comment by MrDuartePT** [comment]
> It definitely doesn't hurt adding it to our repos, but you can say the same to installing it directly from the AUR. I say this because the AUR package does nothing more than:
> 
> 1. Cloning the repo
> 2. Setting the pkgver
> 3. Installing files to the package
> 
> There is no building involved.

Sorry but you are wrong, there is buiding involve on the AUR package:
1 - LenovoLegionLinux-dkms - compile the module on you machine, i don't provided a binary.

2 - LenovoLegionLinux - since the gui and cli are python don't require any compilation but the legiond module requires, since is written in C.

**Comment by MrDuartePT** [comment]
> > > Hey,
> > > We have dropped the patchset, because the driver got loaded, even if there was no lenovo hardware available.
> > 
> > 
> > That is pretty interesting and should never happen. Do you have more details or a user report for that?
> > The driver is probed when there is a device `PNP0C0`. Then the driver checks if the the vendor is `LENOVO` and the BIOS version is in a list of supported BIOS versions (e.g. `HHCN`) via DMI. If this is check is not successful the probe aborts and it will unload.
> 
> Hi,
> 
> This was mainly found on the Steam Deck, when we started to work on the cachyos handheld option. Basically the driver got probed but then failed with an error. Generally this is not problematic, but I dont like to have from a patchset side introduced errors in the kernel.

I agree on you decision is not good have a kernel error on the patchset (even the error are harmeless). I might try to see if I can solve that probing problem, but might be a bit difficult since I don't own a steamdeck (if you can provide logs would be awesome).

Also the driver was design to abort with a error when is not a lenovo device, probably was not a good decision, but well we can try change that to a warning.

**Comment by 1Naim** [comment]
> Sorry but you are wrong, there is buiding involve on the AUR package:
> 1 - LenovoLegionLinux-dkms - compile the module on you machine, i don't provided a binary.

You misunderstand. I wasn't referring to what the package does, but how the package is built. I know that it compiles modules in each system, but the package itself doesn't need to be built.



> 2 - LenovoLegionLinux - since the gui and cli are python don't require any compilation but the legiond module requires, since is written in C.

Yeah, this one needs building.

**Comment by ptr1337** [comment]
> > > > Hey,
> > > > We have dropped the patchset, because the driver got loaded, even if there was no lenovo hardware available.
> > > 
> > > 
> > > That is pretty interesting and should never happen. Do you have more details or a user report for that?
> > > The driver is probed when there is a device `PNP0C0`. Then the driver checks if the the vendor is `LENOVO` and the BIOS version is in a list of supported BIOS versions (e.g. `HHCN`) via DMI. If this is check is not successful the probe aborts and it will unload.
> > 
> > 
> > Hi,
> > This was mainly found on the Steam Deck, when we started to work on the cachyos handheld option. Basically the driver got probed but then failed with an error. Generally this is not problematic, but I dont like to have from a patchset side introduced errors in the kernel.
> 
> I agree on your decision is not good have a kernel error on the patchset (even the error are harmeless). I might try to see if I can solve that probing problem, but might be a bit difficult since I don't own a steamdeck (if you can provide logs would be awesome).
> 
> Also the if driver is giving a error when unloading, we can try change that to warning instead, like "Unsupported device, Unloading the driver".

I dont feel well, pushing git packages into CachyOS with this.
Do you plan to work on an AUR package, which is based on stable releases?
https://aur.archlinux.org/packages/lenovolegionlinux-dkms-git

**Comment by ptr1337** [comment]
Anyways, I have pushed the lenovolegionlinux-dkms-git and lenovolegionlinux-git for now.

**Comment by MrDuartePT** [comment]
> I dont feel well, pushing git packages into CachyOS with this.
> 
> Do you plan to work on an AUR package, which is based on stable releases?
> 
> https://aur.archlinux.org/packages/lenovolegionlinux-dkms-git

We should make a real stable release after this PR is done: https://github.com/johnfanv2/LenovoLegionLinux/pull/261

The tag that exist was because the fedora copr dosen`t accept git packages.
