### ISSUE TITLE
6.11: Hunk failed for amd-pstate

### ISSUE THREAD

**Issue by bermeitinger-b** [CachyOS/kernel-patches#74]
Hi, I'm relatively new to all these custom kernel patching but I am a happy user of your kernel on my arch installation.
I'm using the PKGBUILD from the AUR as a base but inject a custom config (disabling unnecessary modules, etc.).

The AUR's PGKBUILD is using the 6.11's 0001-cachyos-base-all.patch file as the source for the patches. Since today, applying this patch does not work:

```
patching file drivers/cpufreq/amd-pstate.c
Hunk #4 FAILED at 520.
Hunk #5 succeeded at 772 (offset 3 lines).
Hunk #6 succeeded at 800 (offset 3 lines).
Hunk #7 succeeded at 874 (offset 3 lines).
Hunk #8 succeeded at 897 (offset 3 lines).
Hunk #9 succeeded at 955 (offset 3 lines).
Hunk #10 succeeded at 1410 (offset 3 lines).
Hunk #11 succeeded at 1874 (offset 3 lines).
1 out of 11 hunks FAILED -- saving rejects to file drivers/cpufreq/amd-pstate.c.rej
```

Judging from the commit message, amd-pstate should be removed anway, so I'm wondering about this message.

This is the rejected file:
```patch
--- drivers/cpufreq/amd-pstate.c
+++ drivers/cpufreq/amd-pstate.c
@@ -520,12 +486,15 @@ static void amd_pstate_update(struct amd_cpudata *cpudata, u32 min_perf,
 	}
 
 	if (value == prev)
-		return;
+		goto cpufreq_policy_put;
 
 	WRITE_ONCE(cpudata->cppc_req_cached, value);
 
 	amd_pstate_update_perf(cpudata, min_perf, des_perf,
 			       max_perf, fast_switch);
+
+cpufreq_policy_put:
+	cpufreq_cpu_put(policy);
 }
 
 static int amd_pstate_verify(struct cpufreq_policy_data *policy)
```

**Comment by ptr1337** [comment]
Hi, 

We have removed the amd-pstate patch currently, due a regression. Likely you had the old patch still cached?

**Comment by bermeitinger-b** [comment]
Well, how embarassing :+1:  I thought `makepkg` was clever enough to actually download the file.

Thank you very much.
