### ISSUE TITLE
Need adapt 0009-openvpn-dco.patch for kernel version (line) 6.11

### ISSUE THREAD

**Issue by Cerberios** [CachyOS/kernel-patches#78]
Hello there!
Please can you adapt  this patch 0009-openvpn-dco.patch for kernel version (line) 6.11
I've got rejection error when tried to apply.
Thank You very much!

**Comment by ptr1337** [comment]
Hey :)

Unlikely, since it depends on other stuff merged in 6.12. If you want to use DCO, please use the 6.12 Kernel.

I really hope this gets finally merged, but we will see. We wont be able to carry it again for a half a year, till a new rev comes.
