### ISSUE TITLE
It's possible to have a CachyOS version macro

### ISSUE THREAD

**Issue by cyring** [CachyOS/kernel-patches#8]
We have a building [issue](https://github.com/cyring/CoreFreq/issues/417) due to a change in function prototype of `cpufreq_unregister_driver`

Do you have or could you provide a macro like `LINUX_VERSION_CODE` is to test what CachyOS a kernel module is building with ?

Something like `CACHYOS_VERSION`

Regards

**Comment by vnepogodin** [comment]
Hi @cyring

Yes.
We can add `CACHYOS_VERSION` to `<linux/version.h>` to provide information about current release
