### ISSUE TITLE
ovpn-dco not working as expected

### ISSUE THREAD

**Issue by Cerberios** [CachyOS/kernel-patches#81]
Hello there!
Seems some problem with ovpn-dco patch - its not working 
I've applied patch for kernel 6.12-rc7
Selected ovpn-dco as module, compiled and installed.

So, I can see module loaded

**thinkbox /tmp # lsmod | grep -i vpn**
ovpn                  102400  0
ip6_udp_tunnel         16384  1 ovpn
udp_tunnel             36864  1 ovpn

 And when I start OpenVPN 2.6.12 client, I see message

 openvpn[5593]: Note: Kernel support for ovpn-dco missing, disabling data channel offload.
 openvpn[5593]: OpenVPN 2.6.12 x86_64-pc-linux-gnu [SSL (OpenSSL)] [COMP_STUB] [EPOLL] [MH/PKTINFO] [AEAD] [DCO]
 openvpn[5593]: DCO version: N/A

And driver not applied for tun0 device:

**thinkbox /tmp # ethtool -i tun0**
driver: tun
version: 1.6
firmware-version:
expansion-rom-version:
bus-info: tun
supports-statistics: no
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

Please, advice - what can be wrong?
Thanks!

**Comment by Cerberios** [comment]
> Is this reproduceable with our kernel?

Mr. Eric, I am not sure "our" or not.
I've downloaded native kernel from kernel.org site and have applied only 2 patches:
this patch for openvpn-dco + 4567_distro-Gentoo-Kconfig.patch

**Comment by 1Naim** [comment]
https://paste.cachyos.org/p/bcf5052.diff

Can you please test with this older revision of ovpn-dco?

**Comment by Cerberios** [comment]
Sure, will test and report here. May be in a hour or 2. Thanks alot!

**Comment by 1Naim** [comment]
You can also try to use openvpn3 https://codeberg.org/OpenVPN/openvpn3-linux

**Comment by ptr1337** [comment]
Patch will be dropped with upcoming release. The new module does not support DCO in 2.6 (only the dkms one), therefore well drop it.
