### ISSUE TITLE
any chance to update sched-ext for kernel 6.6 (lts)?

### ISSUE THREAD

**Issue by dim-geo** [CachyOS/kernel-patches#84]
https://github.com/CachyOS/kernel-patches/blob/7ed2c2912029bc74b8276b7922164d7b538caea9/6.6/sched/0001-sched-ext.patch#L1

Hi, is there any chance to update sched-ext for 6.6? I don't think it can be applied to lts kernel anymore.

**Comment by 1Naim** [comment]
Nope. Even if the patchset applies, it is heavily outdated now that most scx schedulers won't even run.
