### ISSUE TITLE
 Feature request: tpm: disable hwrng for fTPM on some AMD designs

### ISSUE THREAD

**Issue by road2react** [CachyOS/kernel-patches#9]
The patch is located here: https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-tpmdd.git/commit/?id=ffe4a34b29aa672f1fa05f49a7e4c3ea4ab4e12f

This would fix a problem caused by AMD's fTPM firmware, but is not yet in the main upstream branch. This patch would backport the fix to an already-stable version.

**Comment by ptr1337** [comment]
Hi,

This patchset is already in our fixes branch (github.com/cachyos/linux). Its already used in linux-cachyos since 6.2 :)
